"""add reasoning usage

Revision ID: 2873e4623ed8
Revises: 4a8b671a4336
Create Date: 2026-10-01 01:25:10.397068
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2873e4623ed8'
down_revision: str | None = '4a8b671a4336'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasoning_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('provider_request_id', sa.Text(), nullable=True),
    sa.Column('context_chars', sa.Integer(), nullable=False),
    sa.Column('context_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reasoning_usage_requested_at', 'reasoning_usage', ['requested_at'], unique=False)
    op.create_index('ix_reasoning_usage_status', 'reasoning_usage', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reasoning_usage_status', table_name='reasoning_usage')
    op.drop_index('ix_reasoning_usage_requested_at', table_name='reasoning_usage')
    op.drop_table('reasoning_usage')
    # ### end Alembic commands ###
