"""add event playbooks

Revision ID: 4a8b671a4336
Revises: 20261001_0003
Create Date: 2026-10-01 00:54:12.168438
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4a8b671a4336'
down_revision: str | None = '20261001_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('playbook_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_overlay', sa.Boolean(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playbook_key', 'version', name='uq_playbooks_key_version')
    )
    op.create_index('ix_playbooks_event_type_active', 'playbooks', ['event_type', 'active'], unique=False)
    op.create_table('event_playbooks',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('playbook_id', sa.Uuid(), nullable=False),
    sa.Column('detection_reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'playbook_id')
    )
    op.create_table('playbook_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('playbook_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('typical_owner', sa.Text(), nullable=True),
    sa.Column('ideal_lead_days', sa.Integer(), nullable=True),
    sa.Column('minimum_lead_days', sa.Integer(), nullable=True),
    sa.Column('done_when', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('common_failure_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_expected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sponsor_dependent', sa.Boolean(), nullable=False),
    sa.Column('event_type_specific', sa.Boolean(), nullable=False),
    sa.Column('next_step', sa.Text(), nullable=False),
    sa.Column('evaluation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playbook_id', 'requirement_key', name='uq_playbook_requirements_key')
    )
    op.create_index('ix_playbook_requirements_playbook_id', 'playbook_requirements', ['playbook_id'], unique=False)
    op.create_table('requirement_evaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('complete_count', sa.Integer(), nullable=False),
    sa.Column('in_progress_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('unknown_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('critical_gap_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirement_runs_event_id', 'requirement_evaluation_runs', ['event_id'], unique=False)
    op.create_table('event_requirement_state',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('last_run_id', sa.Uuid(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_run_id'], ['requirement_evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['playbook_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'requirement_id')
    )
    op.create_index('ix_event_requirement_state_status', 'event_requirement_state', ['status'], unique=False)
    op.create_index('ix_event_requirement_state_urgency', 'event_requirement_state', ['urgency'], unique=False)
    op.create_table('requirement_dependencies',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_requirement_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_requirement_id'], ['playbook_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['playbook_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id', 'depends_on_requirement_id')
    )
    op.create_table('requirement_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('readiness_weight', sa.Float(), nullable=False),
    sa.Column('readiness_earned', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['playbook_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['requirement_evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'event_id', 'requirement_id', name='uq_requirement_evaluations_run_event_requirement')
    )
    op.create_index('ix_requirement_evaluations_event_id', 'requirement_evaluations', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requirement_evaluations_event_id', table_name='requirement_evaluations')
    op.drop_table('requirement_evaluations')
    op.drop_table('requirement_dependencies')
    op.drop_index('ix_event_requirement_state_urgency', table_name='event_requirement_state')
    op.drop_index('ix_event_requirement_state_status', table_name='event_requirement_state')
    op.drop_table('event_requirement_state')
    op.drop_index('ix_requirement_runs_event_id', table_name='requirement_evaluation_runs')
    op.drop_table('requirement_evaluation_runs')
    op.drop_index('ix_playbook_requirements_playbook_id', table_name='playbook_requirements')
    op.drop_table('playbook_requirements')
    op.drop_table('event_playbooks')
    op.drop_index('ix_playbooks_event_type_active', table_name='playbooks')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
